import React from 'react';
import { View, Text, ScrollView, Linking, StyleSheet } from 'react-native';

const PrivacyPolicy = () => {
  return ( 
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Privacy Policy</Text>
      <Text style={styles.paragraph}>Last updated: June 24, 2024</Text>
      <Text style={styles.paragraph}>
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </Text>
      <Text style={styles.paragraph}>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the{' '}
        <Text style={styles.link} onPress={() => Linking.openURL('https://www.termsfeed.com/privacy-policy-generator/')}>
          Privacy Policy Generator
        </Text>.
      </Text>

      <Text style={styles.subtitle}>Interpretation and Definitions</Text>
      <Text style={styles.subtitle}>Interpretation</Text>
      <Text style={styles.paragraph}>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </Text>

      <Text style={styles.subtitle}>Definitions</Text>
      <Text style={styles.paragraph}>For the purposes of this Privacy Policy:</Text>
      <View style={styles.list}>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Account</Text> means a unique account created for You to access our Service or parts of our Service.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Affiliate</Text> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Application</Text> refers to Factor, the software program provided by the Company.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Company</Text> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Petrola Serviços Médicos, Rua Martinho Salazar, s/n.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Country</Text> refers to: Brazil
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Device</Text> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Personal Data</Text> is any information that relates to an identified or identifiable individual.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Service</Text> refers to the Application.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Service Provider</Text> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>Usage Data</Text> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>You</Text> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
          </Text>
        </View>
      </View>

      <Text style={styles.subtitle}>Collecting and Using Your Personal Data</Text>
      <Text style={styles.subtitle}>Types of Data Collected</Text>
      <Text style={styles.subtitle}>Personal Data</Text>
      <Text style={styles.paragraph}>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </Text>
      <View style={styles.list}>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>Email address</Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>First name and last name</Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>Phone number</Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>Usage Data</Text>
        </View>
      </View>

      <Text style={styles.subtitle}>Usage Data</Text>
      <Text style={styles.paragraph}>Usage Data is collected automatically when using the Service.</Text>
      <Text style={styles.paragraph}>
        Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </Text>
      <Text style={styles.paragraph}>
        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
      </Text>
      <Text style={styles.paragraph}>
        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
      </Text>

      <Text style={styles.subtitle}>Use of Your Personal Data</Text>
      <Text style={styles.paragraph}>The Company may use Personal Data for the following purposes:</Text>
      <View style={styles.list}>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>To provide and maintain our Service</Text>, including to monitor the usage of our Service.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>To manage Your Account:</Text> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>For the performance of a contract:</Text> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>To contact You:</Text> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
          </Text>
        </View>
        <View style={styles.listItem}>
          <Text style={styles.paragraph}>
            <Text style={{ fontWeight: 'bold' }}>To provide You</Text> with news, special offers
            </Text>
        </View>
      </View>
      <Text style={styles.heading}>Delete Your Personal Data</Text>
      <Text style={styles.paragraph}>
        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
      </Text>
      <Text style={styles.paragraph}>
        Our Service may give You the ability to delete certain information about You from within the Service.
      </Text>
      <Text style={styles.paragraph}>
        You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
      </Text>
      <Text style={styles.paragraph}>
        Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
      </Text>

      <Text style={styles.heading}>Disclosure of Your Personal Data</Text>
      <Text style={styles.subheading}>Business Transactions</Text>
      <Text style={styles.paragraph}>
        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
      </Text>
      <Text style={styles.subheading}>Law enforcement</Text>
      <Text style={styles.paragraph}>
        Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
      </Text>
      <Text style={styles.subheading}>Other legal requirements</Text>
      <Text style={styles.paragraph}>
        The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
      </Text>
      <View style={styles.list}>
        <Text style={styles.listItem}>Comply with a legal obligation</Text>
        <Text style={styles.listItem}>Protect and defend the rights or property of the Company</Text>
        <Text style={styles.listItem}>Prevent or investigate possible wrongdoing in connection with the Service</Text>
        <Text style={styles.listItem}>Protect the personal safety of Users of the Service or the public</Text>
        <Text style={styles.listItem}>Protect against legal liability</Text>
      </View>

      <Text style={styles.heading}>Security of Your Personal Data</Text>
      <Text style={styles.paragraph}>
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
      </Text>

      <Text style={styles.heading}>Children's Privacy</Text>
      <Text style={styles.paragraph}>
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
      </Text>
      <Text style={styles.paragraph}>
        If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
      </Text>

      <Text style={styles.heading}>Links to Other Websites</Text>
      <Text style={styles.paragraph}>
        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
      </Text>
      <Text style={styles.paragraph}>
        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
      </Text>

      <Text style={styles.heading}>Changes to this Privacy Policy</Text>
      <Text style={styles.paragraph}>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
      </Text>
      <Text style={styles.paragraph}>
        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
      </Text>
      <Text style={styles.paragraph}>
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
      </Text>

      <Text style={styles.heading}>Contact Us</Text>
      <Text style={styles.paragraph}>
        If you have any questions about this Privacy Policy, You can contact us:
      </Text>
      <View style={styles.list}>
        <Text style={styles.listItem}>By phone number: +55 (91) 984147769</Text>
      </View>
    </ScrollView>
    );
};

const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: 'white',
    marginHorizontal: 45,
    overflow: 'hidden',
    height: 100,
    borderRadius: 10,
    marginTop: 5,
    borderWidth: 0.8,
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  subheading: {
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 5,
  },
  paragraph: {
    fontSize: 16,
    marginVertical: 5,
    lineHeight: 22,
  },
  list: {
    marginVertical: 5,
    paddingLeft: 20,
  },
  listItem: {
    fontSize: 16,
    marginVertical: 2,
  },
  link: {
    color: 'blue',
    textDecorationLine: 'underline',
  },
    title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
  },
});

export default PrivacyPolicy;